### ISSUE TITLE
cgal add_externalproject

### ISSUE THREAD

**Issue by petrasvestartas** [hshikata/udivone#1]
Hi,

I would like to ask your advice how you would add a dependency of cgal as external project to your project?

I mean this CMakeLists.txt that download dependencies:
https://github.com/hshikata/udivone/blob/daba4ea493189c9e0118328d5f863f6a9f3cbf2e/superbuild/CMakeLists.txt

It is the only good repository that shows good examples for windows, and I am seeking your advice.

**Comment by hshikata** [comment]
Hi.
While I do not have an environment I can try at this moment, I would assume you can take one of the ExternalProject_Add() command as a template. The source code is hosted on github and you should now the version you would like to use. What I did for other 3rd party libraries was that I downloaded the code, and used cmake to configure/build them as standalone. During the process, you should know which "CMAKE_ARGS" you need to set for your purpose. A few parameters are common, but others are library dependent. You might need to change the source code for a particular platform by applying a patch. The CMakeLists.txt contains such case.

```
ExternalProject_Add(cgal
  GIT_REPOSITORY https://github.com/CGAL/cgal.git
  GIT_TAG v5.4.1
  UPDATE_COMMAND ""
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
   # Add args as needed
)
```

Hope this helps.

**Comment by petrasvestartas** [comment]
This worked perfectly thank you
